version: "3"
services:
  web:
    build: .
    ports:
      - "5005:80"
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - .:/app
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
